version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python_simple'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src
      - ./opt:/root/opt
